"""Model registry.

Importing this package is what populates `Base.metadata`. `migrations/env.py`
imports `Base` from here, and with an empty registry Alembic's autogenerate
would see every existing table as unknown and propose dropping it — which is
how a routine migration deletes an audit trail.

`alembic check` is asserted by a test, so a model that drifts from the migration
fails the suite instead of producing an autogenerated migration that drops
tables.
"""

from app.models.audit_log import AuditLog
from app.models.base import Base
from app.models.credential_token import CredentialToken
from app.models.login_attempt import LoginAttempt
from app.models.rate_limit import RateLimit
from app.models.user import User
from app.models.user_session import SessionFamily, UserSession

__all__ = [
    "AuditLog",
    "Base",
    "CredentialToken",
    "LoginAttempt",
    "RateLimit",
    "SessionFamily",
    "User",
    "UserSession",
]
