"""SQLAlchemy ORM models — the schema as Python sees it.

``alembic check`` is asserted by a test, so a model that drifts from the
migration fails the suite instead of producing an autogenerated migration that
drops tables.
"""
