"""Baseline: usuario, credential grants, sessions, throttles, audit trail.

SPEC-0001 v0.5. The project's first migration.

Hand-written rather than autogenerated: partitioning, triggers, generated
columns, a SECURITY DEFINER function and per-role grants are all invisible to
Alembic's comparison. See `docs/architecture/data-model.md` for why each
constraint exists — this file is the mechanism, that file is the argument.

Revision ID: 0001_baseline
Revises:
Create Date: 2026-09-10
"""

from collections.abc import Sequence

from alembic import op

from app.core.config import get_settings

revision: str = "0001_baseline"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# RNF08 retains audit rows for at least five years. Seven partitions cost
# nothing and buy six years of not depending on a scheduled job nobody is
# watching — see `_criar_particoes`.
ANO_INICIAL = 2026
ANO_FINAL = 2032

# Custom SQLSTATEs, so tests assert on a code instead of a Portuguese string.
# Class "SI" is unassigned by the standard and by PostgreSQL.
ERRO_HISTORICO_IMUTAVEL = "SI001"
ERRO_DOWNGRADE_RECUSADO = "SI002"
ERRO_PAPEL_AUSENTE = "SI003"
ERRO_SESSAO_IMUTAVEL = "SI004"
ERRO_ULTIMO_GESTOR = "SI005"


def _papel() -> str:
    return get_settings().db_app_role


def upgrade() -> None:
    """Create the schema, in dependency order, then grant to the app role."""
    _exigir_papel_de_aplicacao()
    _usuario()
    _token_credencial()
    _tentativa_login()
    _limite_taxa()
    _sessoes()
    _historico()
    _conceder_privilegios()


def downgrade() -> None:
    """Refuse to run once the audit trail holds anything (ADR-0004)."""
    _recusar_se_houver_auditoria()
    # Dropping the partitioned parent removes its partitions and the cloned
    # triggers, including any partition a scheduled job created later — which
    # is why this does not enumerate them.
    op.execute("DROP TABLE IF EXISTS historico_movimentacao CASCADE")
    op.execute("DROP FUNCTION IF EXISTS criar_particao_historico(int)")
    op.execute("DROP FUNCTION IF EXISTS fn_historico_imutavel()")
    op.execute("DROP TABLE IF EXISTS sessao CASCADE")
    op.execute("DROP TABLE IF EXISTS sessao_familia CASCADE")
    op.execute("DROP FUNCTION IF EXISTS fn_sessao_imutavel()")
    op.execute("DROP TABLE IF EXISTS limite_taxa CASCADE")
    op.execute("DROP TABLE IF EXISTS tentativa_login CASCADE")
    op.execute("DROP TABLE IF EXISTS token_credencial CASCADE")
    op.execute("DROP TABLE IF EXISTS usuario CASCADE")
    op.execute("DROP FUNCTION IF EXISTS fn_ultimo_gestor()")


# ── preconditions ───────────────────────────────────────────────────────────


def _exigir_papel_de_aplicacao() -> None:
    """Fail loudly if the application role is missing.

    ADR-0004's append-only guarantee assumes the application does not connect
    as the table owner. With a single role, the REVOKE and the trigger below
    are decoration: an owner can DISABLE TRIGGER, TRUNCATE, and re-GRANT
    itself UPDATE. Half-applying this migration is worse than not applying it,
    so it stops here rather than at the GRANT statements.
    """
    op.execute(f"""
        DO $$
        BEGIN
          IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '{_papel()}') THEN
            RAISE EXCEPTION
              'papel de aplicação "%" não existe; rode infra/postgres/init/01-papeis.sh',
              '{_papel()}'
              USING ERRCODE = '{ERRO_PAPEL_AUSENTE}';
          END IF;
        END $$;
    """)


def _recusar_se_houver_auditoria() -> None:
    """A downgrade that destroys the audit trail is not a downgrade."""
    op.execute(f"""
        DO $$
        DECLARE n bigint;
        BEGIN
          IF EXISTS (SELECT 1 FROM information_schema.tables
                     WHERE table_name = 'historico_movimentacao') THEN
            EXECUTE 'SELECT count(*) FROM historico_movimentacao' INTO n;
            IF n > 0 THEN
              RAISE EXCEPTION
                'downgrade recusado: % linhas de auditoria seriam destruídas', n
                USING ERRCODE = '{ERRO_DOWNGRADE_RECUSADO}';
            END IF;
          END IF;
        END $$;
    """)


# ── tables ──────────────────────────────────────────────────────────────────


def _usuario() -> None:
    # perfil and status are VARCHAR + CHECK rather than native ENUM types on
    # purpose. OQ-26 already names two roles the operation needs and this
    # model does not carry yet (comprador, gestor de unidade), so `perfil` is
    # demonstrably not a closed set — and ALTER TYPE ... ADD VALUE cannot run
    # inside a transaction block, which is exactly where Alembic runs.
    op.execute("""
        CREATE TABLE usuario (
          id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
          nome           VARCHAR(200),
          email          VARCHAR(320) UNIQUE,
          senha_hash     VARCHAR(100),
          perfil         VARCHAR(20)  NOT NULL,
          status         VARCHAR(20)  NOT NULL,
          criado_em      TIMESTAMPTZ  NOT NULL DEFAULT now(),
          anonimizado_em TIMESTAMPTZ,
          oidc_subject   VARCHAR(255) UNIQUE,
          ativo     BOOLEAN GENERATED ALWAYS AS (status = 'ativo') STORED,
          pseudonimo TEXT  GENERATED ALWAYS AS
                     ('USR-' || upper(substr(encode(uuid_send(id), 'hex'), 1, 12))) STORED,
          CONSTRAINT ck_usuario_perfil
            CHECK (perfil IN ('gestor', 'servidor', 'auditor')),
          CONSTRAINT ck_usuario_status
            CHECK (status IN ('pendente', 'ativo', 'bloqueado', 'desativado')),
          CONSTRAINT ck_usuario_pendente_sem_credencial
            CHECK (status <> 'pendente' OR senha_hash IS NULL),
          CONSTRAINT ck_usuario_anonimizado
            CHECK (anonimizado_em IS NULL
                   OR (nome IS NULL AND email IS NULL
                       AND senha_hash IS NULL AND oidc_subject IS NULL))
        )
    """)
    op.execute("CREATE UNIQUE INDEX ux_usuario_pseudonimo ON usuario (pseudonimo)")
    _trigger_ultimo_gestor()


def _trigger_ultimo_gestor() -> None:
    """DB13 — at least one `ativo` gestor always exists (AC-0001-29).

    A cross-row aggregate, so a CHECK cannot express it. A trigger alone is
    also not enough: two transactions each removing a different one of two
    gestores both see a count of two and both commit. That is write skew, and
    snapshot isolation does not prevent it. The `ORDER BY id FOR UPDATE` is
    what makes the concurrent case deterministic instead of a deadlock; the
    service additionally takes an advisory lock so the caller sees the 409 the
    spec promises rather than a serialisation failure.
    """
    op.execute(f"""
        CREATE FUNCTION fn_ultimo_gestor() RETURNS trigger
        LANGUAGE plpgsql AS $$
        DECLARE restantes int;
        BEGIN
          IF OLD.perfil = 'gestor' AND OLD.status = 'ativo'
             AND (NEW.status <> 'ativo' OR NEW.perfil <> 'gestor') THEN
            SELECT count(*) INTO restantes FROM (
              SELECT id FROM usuario
              WHERE perfil = 'gestor' AND status = 'ativo' AND id <> OLD.id
              ORDER BY id FOR UPDATE
            ) AS outros;
            IF restantes = 0 THEN
              RAISE EXCEPTION
                'não é possível remover o último gestor ativo'
                USING ERRCODE = '{ERRO_ULTIMO_GESTOR}';
            END IF;
          END IF;
          RETURN NEW;
        END $$;
    """)
    op.execute("""
        CREATE TRIGGER trg_usuario_ultimo_gestor
        BEFORE UPDATE ON usuario
        FOR EACH ROW EXECUTE FUNCTION fn_ultimo_gestor()
    """)
    op.execute("ALTER TABLE usuario ENABLE ALWAYS TRIGGER trg_usuario_ultimo_gestor")


def _token_credencial() -> None:
    # One table for invitations and password resets: same object, same
    # mechanics — a hashed, single-use, expiring grant to set a credential.
    op.execute("""
        CREATE TABLE token_credencial (
          id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
          usuario_id   UUID        NOT NULL REFERENCES usuario (id),
          tipo         VARCHAR(20) NOT NULL,
          token_hash   BYTEA       NOT NULL UNIQUE,
          criado_por   UUID        REFERENCES usuario (id),
          criado_em    TIMESTAMPTZ NOT NULL DEFAULT now(),
          expira_em    TIMESTAMPTZ NOT NULL,
          utilizado_em TIMESTAMPTZ,
          cancelado_em TIMESTAMPTZ,
          CONSTRAINT ck_token_tipo
            CHECK (tipo IN ('convite', 'redefinicao')),
          CONSTRAINT ck_token_expira
            CHECK (expira_em > criado_em),
          CONSTRAINT ck_token_uso_dentro_do_prazo
            CHECK (utilizado_em IS NULL OR utilizado_em <= expira_em),
          CONSTRAINT ck_token_convite_tem_autor
            CHECK (tipo <> 'convite' OR criado_por IS NOT NULL)
        )
    """)
    # One outstanding grant per usuario per type. `cancelado_em` is what makes
    # reissue possible: an expired-unredeemed grant still matches
    # `utilizado_em IS NULL`, and now() cannot appear in an index predicate.
    op.execute("""
        CREATE UNIQUE INDEX ux_token_credencial_aberto
        ON token_credencial (usuario_id, tipo)
        WHERE utilizado_em IS NULL AND cancelado_em IS NULL
    """)


def _tentativa_login() -> None:
    # Keyed on an HMAC of the *submitted* address, not on a usuario. Keying it
    # on the account made AC-0001-02 false: an unknown address had no counter,
    # so six attempts distinguished it from a real one.
    op.execute("""
        CREATE TABLE tentativa_login (
          email_hmac    BYTEA PRIMARY KEY,
          tentativas    INT         NOT NULL DEFAULT 0,
          ultima_em     TIMESTAMPTZ NOT NULL DEFAULT now(),
          bloqueado_ate TIMESTAMPTZ,
          CONSTRAINT ck_tentativa_nao_negativa CHECK (tentativas >= 0)
        )
    """)


def _limite_taxa() -> None:
    # AC-0001-33 / RNF16. `chave` is an HMAC of the source, never the address:
    # an IP identifies a person closely enough to sit in lgpd.md's inventory,
    # and this table is read on every authentication request.
    op.execute("""
        CREATE TABLE limite_taxa (
          chave         BYTEA        NOT NULL,
          rota          VARCHAR(120) NOT NULL,
          janela_inicio TIMESTAMPTZ  NOT NULL,
          contador      INT          NOT NULL DEFAULT 0,
          PRIMARY KEY (chave, rota, janela_inicio),
          CONSTRAINT ck_limite_contador CHECK (contador >= 0)
        )
    """)
    # For the purge job. This table grows with traffic and nothing keeps it
    # healthy except that job — ADR-0012 records it as a follow-up.
    op.execute("CREATE INDEX ix_limite_taxa_janela ON limite_taxa (janela_inicio)")


def _sessoes() -> None:
    op.execute("""
        CREATE TABLE sessao_familia (
          familia     UUID PRIMARY KEY,
          usuario_id  UUID        NOT NULL REFERENCES usuario (id),
          criada_em   TIMESTAMPTZ NOT NULL DEFAULT now(),
          revogada_em TIMESTAMPTZ,
          CONSTRAINT uq_sessao_familia_usuario UNIQUE (familia, usuario_id)
        )
    """)
    # The composite FK is DB11: without it one family could span two users,
    # and revoking it would revoke another person's sessions.
    op.execute("""
        CREATE TABLE sessao (
          id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
          usuario_id         UUID        NOT NULL,
          familia            UUID        NOT NULL,
          geracao            SMALLINT    NOT NULL,
          refresh_token_hash BYTEA       NOT NULL UNIQUE,
          emitido_em         TIMESTAMPTZ NOT NULL DEFAULT now(),
          expira_em          TIMESTAMPTZ NOT NULL,
          revogado_em        TIMESTAMPTZ,
          revogado_motivo    VARCHAR(20),
          CONSTRAINT uq_sessao_geracao UNIQUE (familia, geracao),
          CONSTRAINT fk_sessao_familia
            FOREIGN KEY (familia, usuario_id)
            REFERENCES sessao_familia (familia, usuario_id),
          CONSTRAINT ck_sessao_expira   CHECK (expira_em > emitido_em),
          CONSTRAINT ck_sessao_revogado CHECK (revogado_em IS NULL OR revogado_em >= emitido_em),
          CONSTRAINT ck_sessao_motivo_valor
            CHECK (revogado_motivo IN
                   ('rotacao', 'logout', 'replay', 'desativacao', 'bloqueio', 'redefinicao')),
          CONSTRAINT ck_sessao_motivo_par
            CHECK ((revogado_em IS NULL) = (revogado_motivo IS NULL))
        )
    """)
    op.execute("CREATE INDEX ix_sessao_familia_ativa ON sessao (familia) WHERE revogado_em IS NULL")
    op.execute(
        "CREATE INDEX ix_sessao_usuario_ativa ON sessao (usuario_id) WHERE revogado_em IS NULL"
    )
    op.execute("CREATE INDEX ix_sessao_expira ON sessao (expira_em)")

    # DB10. "Never un-revoked" was too narrow: it left familia, usuario_id,
    # refresh_token_hash and emitido_em mutable.
    op.execute(f"""
        CREATE FUNCTION fn_sessao_imutavel() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
          IF NEW.id <> OLD.id
             OR NEW.usuario_id <> OLD.usuario_id
             OR NEW.familia <> OLD.familia
             OR NEW.geracao <> OLD.geracao
             OR NEW.refresh_token_hash <> OLD.refresh_token_hash
             OR NEW.emitido_em <> OLD.emitido_em
             OR NEW.expira_em <> OLD.expira_em
             OR (OLD.revogado_em IS NOT NULL AND NEW.revogado_em IS NULL) THEN
            RAISE EXCEPTION
              'sessao accepts changes to revogado_em/revogado_motivo only, '
              'and a revocation does not undo'
              USING ERRCODE = '{ERRO_SESSAO_IMUTAVEL}';
          END IF;
          RETURN NEW;
        END $$;
    """)
    op.execute("""
        CREATE TRIGGER trg_sessao_imutavel
        BEFORE UPDATE ON sessao
        FOR EACH ROW EXECUTE FUNCTION fn_sessao_imutavel()
    """)
    op.execute("ALTER TABLE sessao ENABLE ALWAYS TRIGGER trg_sessao_imutavel")


def _historico() -> None:
    # PRIMARY KEY (id, ocorrido_em), not (id): PostgreSQL refuses a unique
    # constraint on a partitioned table that omits a partitioning column. The
    # documented `id UUID PK` would have failed at CREATE TABLE.
    #
    # The column is `ocorrido_em`, not `timestamp`: TIMESTAMP is a type name,
    # and `PARTITION BY RANGE (timestamp)` is where the parser expects one.
    #
    # `usuario_id` is nullable because AC-0001-20 and AC-0001-21 both audit
    # callers who have no account. ON DELETE stays NO ACTION, which is what
    # makes invariant I4 a database fact.
    op.execute("""
        CREATE TABLE historico_movimentacao (
          id               UUID        NOT NULL DEFAULT gen_random_uuid(),
          ocorrido_em      TIMESTAMPTZ NOT NULL,
          entidade_tipo    VARCHAR(40) NOT NULL,
          entidade_id      UUID        NOT NULL,
          acao             VARCHAR(60) NOT NULL,
          usuario_id       UUID        REFERENCES usuario (id),
          dados_anteriores JSONB,
          justificativa    TEXT,
          correlation_id   UUID        NOT NULL,
          PRIMARY KEY (id, ocorrido_em),
          CONSTRAINT ck_hist_acao_forma       CHECK (acao ~ '^[a-z_]+\\.[a-z_]+$'),
          CONSTRAINT ck_hist_entidade_forma   CHECK (entidade_tipo ~ '^[a-z_]+$')
        ) PARTITION BY RANGE (ocorrido_em)
    """)
    # No `DESC` on `ocorrido_em`: with equality on the leading columns a btree
    # scans backwards just as well, so it bought nothing and only made the
    # models diverge from the schema — which `alembic check` caught.
    for cols in (
        "(entidade_tipo, entidade_id, ocorrido_em)",
        "(usuario_id, ocorrido_em)",
        "(correlation_id)",
    ):
        nome = "ix_hist_" + cols.strip("()").split(",")[0].replace(" ", "")
        op.execute(f"CREATE INDEX {nome} ON historico_movimentacao {cols}")

    op.execute(f"""
        CREATE FUNCTION fn_historico_imutavel() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
          RAISE EXCEPTION 'historico_movimentacao é append-only (%)', TG_OP
            USING ERRCODE = '{ERRO_HISTORICO_IMUTAVEL}';
        END $$;
    """)
    # A row trigger on the parent is cloned to existing partitions and to any
    # partition created or attached later. ENABLE ALWAYS so that
    # session_replication_role = 'replica' does not switch it off.
    op.execute("""
        CREATE TRIGGER trg_historico_imutavel
        BEFORE UPDATE OR DELETE ON historico_movimentacao
        FOR EACH ROW EXECUTE FUNCTION fn_historico_imutavel()
    """)
    op.execute("ALTER TABLE historico_movimentacao ENABLE ALWAYS TRIGGER trg_historico_imutavel")

    _funcao_criar_particao()
    _criar_particoes()


def _funcao_criar_particao() -> None:
    """Idempotent partition creation, owned by the migration role.

    SECURITY DEFINER because the application role has no DDL and must never
    get any. Re-applies the narrow grant and ENABLE ALWAYS rather than
    trusting the clone to carry them.
    """
    op.execute(f"""
        CREATE FUNCTION criar_particao_historico(ano int) RETURNS void
        LANGUAGE plpgsql SECURITY DEFINER AS $$
        DECLARE nome text := format('historico_movimentacao_%s', ano);
        BEGIN
          IF EXISTS (SELECT 1 FROM pg_class WHERE relname = nome) THEN
            RETURN;
          END IF;
          -- Bounds in explicit UTC. A bare date literal against TIMESTAMPTZ
          -- resolves in the creating session's TimeZone, and this project sets
          -- America/Sao_Paulo everywhere, which would land them at 03:00 UTC.
          EXECUTE format(
            'CREATE TABLE %I PARTITION OF historico_movimentacao '
            'FOR VALUES FROM (%L) TO (%L)',
            nome,
            format('%s-01-01 00:00:00+00', ano),
            format('%s-01-01 00:00:00+00', ano + 1));
          EXECUTE format('GRANT SELECT, INSERT ON %I TO {_papel()}', nome);
          EXECUTE format(
            'ALTER TABLE %I ENABLE ALWAYS TRIGGER trg_historico_imutavel', nome);
        END $$;
    """)


def _criar_particoes() -> None:
    """Seven partitions now, rather than a cron job nobody is watching.

    Nothing creates next year's partition automatically, and an INSERT with no
    matching partition fails. Because every write in SIGI records its history
    row in the same transaction, that failure is not localised: every write
    endpoint would start returning 500 at midnight on 1 January.
    """
    for ano in range(ANO_INICIAL, ANO_FINAL + 1):
        op.execute(f"SELECT criar_particao_historico({ano})")


# ── privileges ──────────────────────────────────────────────────────────────


def _conceder_privilegios() -> None:
    papel = _papel()
    # Rows, never structure. No CREATE, no TRUNCATE, no DDL anywhere.
    for tabela, privs in (
        # No DELETE: AC-0001-14 replaces deletion with anonymisation, so the
        # privilege has no legitimate use and its absence is what makes I4 hold.
        ("usuario", "SELECT, INSERT, UPDATE"),
        ("token_credencial", "SELECT, INSERT, UPDATE"),
        # Operational scratch, purged in place.
        ("tentativa_login", "SELECT, INSERT, UPDATE, DELETE"),
        ("limite_taxa", "SELECT, INSERT, UPDATE, DELETE"),
        # Sessions are evidence of a login; they are revoked, not removed.
        ("sessao_familia", "SELECT, INSERT, UPDATE"),
        ("sessao", "SELECT, INSERT, UPDATE"),
    ):
        op.execute(f"GRANT {privs} ON {tabela} TO {papel}")

    # The audit trail: append and read, and that is all. Stated as a REVOKE as
    # well as a narrow GRANT because privileges are per-partition and a later
    # `GRANT ... ON ALL TABLES IN SCHEMA public` is the line every convenience
    # script contains.
    op.execute(f"GRANT SELECT, INSERT ON historico_movimentacao TO {papel}")
    op.execute(f"REVOKE UPDATE, DELETE, TRUNCATE ON historico_movimentacao FROM {papel}")
